---
- name: Extract Executable from PCAP using tcpdump
  hosts: remote_servers
  gather_facts: no
  tasks:
    - name: Install tcpflow
      become: yes
      package:
        name: tcpflow
        state: present

    - name: Collect PCAP file
      ansible.builtin.fetch:
        src: "/home/sempaynado/captured.pcap"
        dest: "/home/sempaynado/HOA8.1/"
        flat: yes

    - name: Debug
      ansible.builtin.debug:
        msg: "Before executing the tcpflow"

    - name: Start and Manual PCAP capture
      command: sudo tcpflow -C -i enp0s8 -o /home/sempaynado/captured.pcap

- hosts: localhost
  connection: local
  gather_facts: false
  tasks:

    - name: Extract potential executables using tcpflow
      command: "tcpflow -r /home/sempaynado/captures.pcap -o /home/sempaynado/HOA8.1/log"
      args:
        created: /home/sempaynado/Documents/collected.exe
